// <auto-generated />
using System;
using Generify.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Generify.Repositories.Migrations
{
    [DbContext(typeof(GenerifyDataContext))]
    partial class GenerifyDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Generify.Models.Management.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Generify.Models.Playlists.OrderInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("OrderDirection")
                        .HasColumnType("int");

                    b.Property<int>("OrderNr")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<Guid>("PlaylistDefinitionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistDefinitionId");

                    b.ToTable("OrderInstructions");
                });

            modelBuilder.Entity("Generify.Models.Playlists.PlaylistDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("TargetPlaylistId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlaylistDefinitions");
                });

            modelBuilder.Entity("Generify.Models.Playlists.PlaylistSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("InclusionType")
                        .HasColumnType("int");

                    b.Property<int>("OrderNr")
                        .HasColumnType("int");

                    b.Property<Guid>("PlaylistDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistDefinitionId");

                    b.ToTable("PlaylistSources");
                });

            modelBuilder.Entity("Generify.Models.Playlists.OrderInstruction", b =>
                {
                    b.HasOne("Generify.Models.Playlists.PlaylistDefinition", "PlaylistDefinition")
                        .WithMany("OrderInstructions")
                        .HasForeignKey("PlaylistDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaylistDefinition");
                });

            modelBuilder.Entity("Generify.Models.Playlists.PlaylistDefinition", b =>
                {
                    b.HasOne("Generify.Models.Management.User", "User")
                        .WithMany("PlaylistDefinitions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Generify.Models.Playlists.PlaylistSource", b =>
                {
                    b.HasOne("Generify.Models.Playlists.PlaylistDefinition", "PlaylistDefinition")
                        .WithMany("PlaylistSources")
                        .HasForeignKey("PlaylistDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaylistDefinition");
                });

            modelBuilder.Entity("Generify.Models.Management.User", b =>
                {
                    b.Navigation("PlaylistDefinitions");
                });

            modelBuilder.Entity("Generify.Models.Playlists.PlaylistDefinition", b =>
                {
                    b.Navigation("OrderInstructions");

                    b.Navigation("PlaylistSources");
                });
#pragma warning restore 612, 618
        }
    }
}
